all:
  vars:
    control_plane_endpoint: 192.168.0.119
    load_balancer_ip_pool:
      - 192.168.0.224/28
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.115, mac: '18:66:da:36:4f:35', disk: sda, network_interface: enp0s31f6}
        metal1: {ansible_host: 192.168.0.116, mac: '18:66:da:36:08:60', disk: sda, network_interface: enp0s31f6}
        metal2: {ansible_host: 192.168.0.117, mac: '18:66:da:36:43:37', disk: sda, network_interface: enp0s31f6}
    workers:
      hosts:
        metal3: {ansible_host: 192.168.0.118, mac: '18:66:da:36:57:63', disk: sda, network_interface: enp0s31f6}
